project:
  type: website

website:
  title: "DSAN5000-Lab1.2"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.ipynb
        text: about
      - href: ./slides/slides.ipynb
        text: slides

format:
  html:
    theme: cosmo
    toc: true



